name: build action

on:
  push:
    branches: [dev2_logging]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: ''

jobs:
  build_1:
    runs-on: ubuntu-latest
    steps:
        - name: Check Out Repo
          uses: actions/checkout@v2

        - name: Docker Login
          uses: docker/login-action@v1.10.0
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1

        # SCANNER BUILD
        - name: Build and push mywish scanner
          id: docker_scanner_build
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/mywish_scanner:latest

        - name: Image digest
          run: echo ${{ steps.docker_scanner_build.outputs.digest }}
